### PR TITLE
added feat.rich-text, tools.notion, workflows.para, edited feat.markdown, feat.plain-text

### PR DESCRIPTION
**Pull request by jpknwls**

### CODE REVIEW

**Comment by kevinslin** [comment]
@jpknwls i made some updates to the dendron-cli dependency this morning so it has the latest template version. can you rebase using the github application? see https://stackoverflow.com/questions/37492908/is-there-a-way-to-make-github-desktop-rebase-a-branch-against-master

**Comment by jpknwls** [comment]
> @jpknwls i made some updates to the dendron-cli dependency this morning so it has the latest template version. can you rebase using the github application? see https://stackoverflow.com/questions/37492908/is-there-a-way-to-make-github-desktop-rebase-a-branch-against-master

Can do, which branch should I rebase on?

**Comment by kevinslin** [comment]
> > @jpknwls i made some updates to the dendron-cli dependency this morning so it has the latest template version. can you rebase using the github application? see https://stackoverflow.com/questions/37492908/is-there-a-way-to-make-github-desktop-rebase-a-branch-against-master
> 
> Can do, which branch should I rebase on?



> > @jpknwls i made some updates to the dendron-cli dependency this morning so it has the latest template version. can you rebase using the github application? see https://stackoverflow.com/questions/37492908/is-there-a-way-to-make-github-desktop-rebase-a-branch-against-master
> 
> Can do, which branch should I rebase on?

main

**Comment by benhsm** [comment]
One thing I'm not sure about is whether or not the use of the first person in much of this content is what we want here- it might be, but I find it a little odd for what this site is. It might be good if we could discuss this and standardize one way or another.

**Comment by jpknwls** [comment]
> One thing I'm not sure about is whether or not the use of the first person in much of this content is what we want here- it might be, but I find it a little odd for what this site is. It might be good if we could discuss this and standardize one way or another.

Good point. I tend to make heavy use of "we", but it's a personal stylistic choice. I don't see a lot of first-person language across the rest of the site, which makes some sense. To pushback slightly, I do think we are talking about *personal* knowledge management, so I don't find it incredibly odd to address the *person* behind the tools-who benefits from the features, participates in workflows, etc. 

But I think it would be worth trying to come up with some loose style guidelines, or I might just need to familiarize myself more with the voice of the site.

**Comment by kevinslin** [comment]
> > One thing I'm not sure about is whether or not the use of the first person in much of this content is what we want here- it might be, but I find it a little odd for what this site is. It might be good if we could discuss this and standardize one way or another.
> 
> Good point. I tend to make heavy use of "we", but it's a personal stylistic choice. I don't see a lot of first-person language across the rest of the site, which makes some sense. To pushback slightly, I do think we are talking about _personal_ knowledge management, so I don't find it incredibly odd to address the _person_ behind the tools-who benefits from the features, participates in workflows, etc.
> 
> But I think it would be worth trying to come up with some loose style guidelines, or I might just need to familiarize myself more with the voice of the site.

Some thoughts:

> Good point. I tend to make heavy use of "we", but it's a personal stylistic choice.

i tend to do this as well. i'm open to either as long as we are consistent. unless we have a good choice not to, would bias to whats already there (non-first person - we can save that for blog posts)

**Pull request closed without merging**
